#!/bin/bash
if [ "$1" == "init" -o ! -f configure ]; then
	libtoolize
	aclocal -I m4
	autoheader
	automake --add-missing
	autoconf
fi
./configure --prefix=/tmp/hector --enable-debug --with-java-include-dir=/usr/lib/jvm/java-6-sun/include/ --with-java-lib-dir=/usr/lib/jvm/java-6-sun/lib/

